### ISSUE TITLE
Error when running the tool

### ISSUE THREAD

**Issue by Droidzzzio** [projectdiscovery/dnsprobe#4] opened 2020-04-05 04:17 UTC
Hey , i am running this tool in windows 10
Go installed with version 1.13+

 Error: open /etc/resolv.conf: The system cannot find the path specified.

Please help me resolving it , because this path is contained in linux.

**Comment by Mzack9999** [comment] 2020-04-05 17:23
Hi @Droidzzzio - Thanks for pointing out the issue! Windows compatibility will be added shortly in the next commit. The tool is still in BETA so your input is highly appreciated!

**Comment by Mzack9999** [comment] 2020-04-05 17:43
@Droidzzzio this should be fixed now!

**Comment by Droidzzzio** [comment] 2020-04-05 17:45
Let me check for once....

Thanks for the reply .I will give the feedback ASAP

**Comment by Droidzzzio** [comment] 2020-04-06 08:11
i have checked and sorry to say but still it is not working and i am getting the same error, update done 

OS: Windows 10 
Go version : latest

**Comment by Droidzzzio** [comment] 2020-04-06 08:11
2020/04/06 13:38:15 Error: open /etc/resolv.conf: The system cannot find the path specified.

**Comment by ehsandeep** [comment] 2020-04-06 10:23
```
C:\Users\MASTERCASE DF-500\go\src\github.com\projectdiscovery\dnsprobe>cat 1.txt | dnsprobe.exe
www.hackerone.com 104.16.99.52
www.hackerone.com 104.16.100.52
docs.hackerone.com 185.199.108.153
docs.hackerone.com 185.199.110.153
docs.hackerone.com 185.199.109.153
docs.hackerone.com 185.199.111.153

C:\Users\MASTERCASE DF-500\go\src\github.com\projectdiscovery\dnsprobe>cat 1.txt | dnsprobe.exe -r cname
docs.hackerone.com hacker0x01.github.io.

C:\Users\MASTERCASE DF-500\go\src\github.com\projectdiscovery\dnsprobe>  
```

```
C:\Users\MASTERCASE DF-500\go\src\github.com\projectdiscovery\dnsprobe>go version
go version go1.13.6 windows/amd64
```

I can confirm this works for me on windows 10 @Droidzzzio @Mzack9999

**Comment by Mzack9999** [comment] 2020-04-06 11:09
@Droidzzzio I also confirm this is working on a fresh installation of Windows. I think that probably your local codebase isn't updated. I suggest to clone the repository again, or anyway ensure that the latest local git commit matches the latest of this repo. This is particularly true for `https://github.com/projectdiscovery/retryabledns` which is the library used by this tool. Let me know if you still meet any problem, I'd be glad to help. Thanks!

**Comment by Droidzzzio** [comment] 2020-04-06 11:15
Thanks for the update and yeah I can assume where the problem lies ,
actually after installing it with go command and executing the next command
which is go build . Is creating a exe file of dnsprobe in the same
directory .
.
.and my gopath is already set in environment variables path

So the problem lying here is that whenever I am calling dnsprobe from any
directory it is picking up the go file of the main program rather than the
exe file of dnsprobe
.
So the simple solution is that if I change the directory of dnsprobe.exe or
if I call specifically dnsprobe.exe rather than dnsprobe then surely it
will work as expected .

I am totally relying on this perception although I will check once and let
you know ASAP

Thank you

**Comment by Droidzzzio** [comment] 2020-04-06 11:26
Thank You  for the guide, the tool is now absolutely working fine i guess the problem was with installing dnsprobe with the older version of git .. I updated git and then again installed it with go command and now the tool is running without any issue

thanks a lot, it was nice talking to you

**Comment by Mzack9999** [comment] 2020-04-06 11:26
Thanks for the feedback @Droidzzzio. Shortly the tool will be finalized and build automated. Don't hesitate to reach out if we can provide any help!

**Closed as completed** 2020-04-06 11:28 UTC
Labels: bug
